### ISSUE TITLE
实测发现使用FTX子账户的情况下，持仓回报没有

### ISSUE THREAD

**Issue by meteorliu80** [hall130/vnpy_ftx#1]
我测试了算法交易，没有成交回报仓位数据，导致疯狂成交。
能否帮忙调试修改下？

**Comment by hall130** [comment]
登录子账号和开启杠杠倍率都是属于行情api部分，与交易模块是没有关系的，vnpy是通过本地仓位信号控制，建议你可以检查一下你的本地交易模块中self.pos返回数据
